<html>

<head>
<title>Empty Sky Go Club</title>

<link rel="stylesheet" href="/new/style.css" type="text/css">
<script type="text/javascript" src="/new/jquery.js"></script>
<script>
eidogoConfig = {enableShortcuts: true};
</script>
<script type="text/javascript" src="http://eidogo.com/player/js/all.compressed.js"></script>
</head>
<body>

<h1>Empty Sky Go Club</h1>

<div id="nav">
<ul>
    <li><a href="/wherewhen.phtml">Where &amp; When We Play</a></li>
    <li><a href="/members.phtml">Our Members</a></li>
    <li><a href="/league">League</a></li>
    <li><a href="mailto:president@emptysky.org">Contact Us</a></li>
    <li><a href="/join.php">Mailing List</a></li>

    <li><a href="/links.html">Go Links</a></li>
</ul>
</div>

<div id="content">

<img src="images/komusou.gif" width="106" height="196" border="0" alt="drawn by David Boyer" align="right" hspace="20">

<img src="images/bullet2.gif" width="8" height="12" border="0" alt=""> <strong><big><big>WHERE &amp; WHEN WE PLAY</big></big></strong><br><br>

We meet every Monday and Thursday night in Java Wally's from 6-9PM, the RIT coffee shop located in Wallace Library (building 5).

<br><br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img src="images/bullet.gif" width="8" height="9" border="0" alt=""> <a href="http://inside.rit.edu/maps/">Directions to RIT</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img src="images/bullet.gif" width="8" height="9" border="0" alt=""> <a href="images/campus_map.gif">Campus map (building 5 highlighted)</a><br>

<br>
<br>

During the summer (June-August) we meet at the <a href="http://www.bupapub.com">ButaPub</a> Tuesday nights from 6-9PM.
<div>

</font>

<br><br>

<small><div align="center">"Komusou" drawn by David Boyer</div></small>

<br><br>
</td><td><img src="images/pixel_trans.gif" width="55" height="1" border="0" alt=""></td></tr></table>
</div>

</body>
</html>
