<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<title>Empty Sky Go Club</title>
<link rel="stylesheet" href="/new/style.css" type="text/css">
<script type="text/javascript" src="/new/jquery.js"></script>
<script>
eidogoConfig = {enableShortcuts: true};
</script>
<script type="text/javascript" src="http://eidogo.com/player/js/all.compressed.js"></script>
</head>
<body>

<h1>Empty Sky Go Club</h1>

<div id="nav">
<ul>
    <li><a href="/wherewhen.phtml">Where &amp; When We Play</a></li>
    <li><a href="/members.phtml">Our Members</a></li>
    <li><a href="/league">League</a></li>
    <li><a href="mailto:emptyskygo@gmail.com">Contact Us</a></li>
    <li><a href="/join.php">Mailing List</a></li>
    <li><a href="/links.html">Go Links</a></li>
</ul>
</div>

<div id="content">
